### ISSUE TITLE
Pytorch的C扩展相关资料

### ISSUE THREAD

**Issue by lshiwjx** [1zb/deformable-convolution-pytorch#3]
请问哪里有Pytorch的C扩展相关文档或样例，官方给的GitHub例子太简单了，你是直接根据那个写出来的吗？

**Comment by 1zb** [comment]
有几个例子可以参考
https://github.com/locuslab/pytorch_fft
https://github.com/fxia22/stn.pytorch

**Comment by lshiwjx** [comment]
请问THArgCheck的第二个参数是什么意思啊，我找了好久也没弄明白。。。是参数的数量吗？哪个参数呢。

**Comment by 1zb** [comment]
表示第x个参数出错了，会显示在错误信息里
