### ISSUE TITLE
How does num_deformable_groups work?

### ISSUE THREAD

**Issue by victorhcm** [1zb/deformable-convolution-pytorch#5]
First off, thank you for your amazing port, @1zb! 

How does `num_deformable_groups` work? I was wondering if it is splitting the offsets, thus each group of input channels will have a given set of offsets (which may be different from other groups). For instance, if we have an input of  6 channels `(1, 6, H, W)`, and `num_deformable_groups=2`, then we would have our input split between two tensors of `(1, 3, H, W)` and `(1, 3, H, W)`, each with its respective instance of offset mask `(1, 3, kH, kW)`. Is that correct?

**Comment by 1zb** [comment]
Yes. You are right. 

`inC` must be divisible by `num_deformable_groups`. Then each group has their own offset.

**Comment by victorhcm** [comment]
Thank you!

**Comment by victorhcm** [comment]
Sorry for bothering you again with this, @1zb, I have a follow up question. In the [mxnet repository](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/deformable_convolution.cc#L84-L94), the authors provide two options, `num_group` and `num_deformable_group`. According to their definition, `num_group` splits the input data, while `num_deformable_group` splits the output tensor and applies the i-th offset group to the i-th output group. 

Thus, here in this repository, is `num_deformable_group` actually equivalent to `num_group` in the original implementation, as it is splitting the input data instead of output?

**Comment by 1zb** [comment]
Thanks for your response.

According to [these lines](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/deformable_convolution-inl.h#L394-L395) and [these lines](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/nn/deformable_im2col.cuh#L311), the parameter `num_deformable_group` splits the input tensor along channel axis, which contradicts [the definition](https://github.com/apache/incubator-mxnet/blob/master/src/operator/contrib/deformable_convolution.cc#L90-L94). I will take a look at the code again.

The parameter `num_group` or `groups` exists in [vanilla CNN](http://pytorch.org/docs/master/nn.html#conv2d). You might find useful discussions [here](https://github.com/BVLC/caffe/issues/778).

**Comment by victorhcm** [comment]
I think you're right, it does seem to be splitting the input tensor. I should check their model to see how they are being used, to make sure.

Thank you for the `num_group` links, by the way!
